/**
 * PDF Export Service
 * ─────────────────
 * Generates a downloadable PDF of a trip plan using PDFKit.
 */

const PDFDocument = require('pdfkit');
const logger = require('../config/logger');

class PDFService {
  generateTripPDF(trip, stream) {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true });
      doc.pipe(stream);

      // Title
      doc.fontSize(24).font('Helvetica-Bold').text('Trip Planner', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(18).text(`${trip.input.startLocation.name} → ${trip.input.destination.name}`, { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(11).font('Helvetica')
        .text(`${new Date(trip.input.startDate).toLocaleDateString()} - ${new Date(trip.input.endDate).toLocaleDateString()} | Budget: ${trip.input.budget.amount} ${trip.input.budget.currency} | Travelers: ${trip.input.travelers}`, { align: 'center' });
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#cccccc');
      doc.moveDown(1);

      // AI Summary
      if (trip.aiItinerary?.summary) {
        doc.fontSize(14).font('Helvetica-Bold').text('Trip Summary');
        doc.moveDown(0.3);
        doc.fontSize(10).font('Helvetica').text(trip.aiItinerary.summary);
        doc.moveDown(1);
      }

      // Transport options
      doc.fontSize(14).font('Helvetica-Bold').text('Transport Options');
      doc.moveDown(0.3);
      if (trip.transport?.driving) {
        doc.fontSize(10).font('Helvetica').text(`🚗 Driving: ${trip.transport.driving.distance?.text || 'N/A'}, ${trip.transport.driving.duration?.text || 'N/A'}`);
      }
      (trip.transport?.flights || []).slice(0, 3).forEach(f => {
        doc.fontSize(10).text(`✈️ ${f.airline} ${f.flightNumber}: ${f.price.amount} ${f.price.currency}`);
      });
      (trip.transport?.trains || []).slice(0, 3).forEach(t => {
        doc.fontSize(10).text(`🚂 ${t.name}: ${t.price.low}-${t.price.high} ${t.price.currency}`);
      });
      doc.moveDown(1);

      // Hotels
      if (trip.hotels?.length) {
        doc.fontSize(14).font('Helvetica-Bold').text('Hotels');
        doc.moveDown(0.3);
        trip.hotels.slice(0, 5).forEach(h => {
          doc.fontSize(10).font('Helvetica').text(`${h.name} - ${h.price.perNight} ${h.price.currency}/night (${h.starRating || 'N/A'} stars)`);
        });
        doc.moveDown(1);
      }

      // Places to visit
      if (trip.places?.length) {
        doc.fontSize(14).font('Helvetica-Bold').text('Places to Visit');
        doc.moveDown(0.3);
        trip.places.slice(0, 10).forEach(p => {
          doc.fontSize(10).font('Helvetica').text(`• ${p.name} (${p.category})`);
        });
        doc.moveDown(1);
      }

      // Day-wise itinerary (moderate tier)
      const plan = trip.aiItinerary?.budgetTiers?.moderate?.dayWisePlan || [];
      if (plan.length) {
        doc.addPage();
        doc.fontSize(16).font('Helvetica-Bold').text('Day-wise Itinerary', { align: 'center' });
        doc.moveDown(1);
        plan.forEach(day => {
          doc.fontSize(12).font('Helvetica-Bold').text(`Day ${day.day}: ${day.title || ''}`);
          (day.activities || []).forEach(act => {
            doc.fontSize(10).font('Helvetica').text(`  ${act.time} - ${act.activity} (${act.location || ''})`);
          });
          doc.moveDown(0.5);
        });
      }

      // Footer
      const pages = doc.bufferedPageRange();
      for (let i = pages.start; i < pages.start + pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).font('Helvetica').text(`Generated by AI Trip Planner | Trip ID: ${trip.tripId}`, 50, doc.page.height - 50, { align: 'center' });
      }

      doc.end();
      return doc;
    } catch (error) {
      logger.error('PDF generation error:', error.message);
      throw error;
    }
  }
}

module.exports = new PDFService();
